const { queryDB } = require("../utils/db");

async function listarMarcacoes({ dataInicial, dataFinal }) {

  let sql = `
  SELECT
    M.MAR_CODIGO,
    M.MAR_MEDICO,
    M.MAR_DATA,
    M.MAR_LIGOU,
    M.MAR_CADASTRO,
    SUBSTRING(M.MAR_HORA FROM 1 FOR 5) AS MAR_HORA,
    TRIM(CAST(CAST(M.MAR_NOME AS VARCHAR(120) CHARACTER SET OCTETS) AS VARCHAR(120) CHARACTER SET WIN1252)) AS NOME_PACIENTE,
    TRIM(CAST(CAST(M.MAR_TELEFONE AS VARCHAR(20) CHARACTER SET OCTETS) AS VARCHAR(20) CHARACTER SET WIN1252)) AS MAR_CEL,
    M.MAR_ESP,
    TRIM(CAST(CAST(DC.MED_NOME AS VARCHAR(120) CHARACTER SET OCTETS) AS VARCHAR(120) CHARACTER SET WIN1252)) AS MEDICO_NOME,
    TRIM(CAST(CAST(L.LOC_NOME AS VARCHAR(120) CHARACTER SET OCTETS) AS VARCHAR(120) CHARACTER SET WIN1252)) AS LOCAL_NOME,
    TRIM(CAST(CAST(E.ESP_NOME AS VARCHAR(120) CHARACTER SET OCTETS) AS VARCHAR(120) CHARACTER SET WIN1252)) AS ESP_NOME
FROM MARCACAO M
LEFT JOIN MEDICO DC ON DC.MED_CODIGO = M.MAR_MEDICO
LEFT JOIN LOCAL L ON L.LOC_CODIGO = M.MAR_LOCAL
LEFT JOIN ESPECIALIDADE E ON E.ESP_CODIGO = M.MAR_ESP
WHERE 1=1

  `;

  if (dataInicial && dataFinal) {
    sql += ` AND M.MAR_DATA BETWEEN '${dataInicial}' AND '${dataFinal}' `;
  }

  sql += " ORDER BY M.MAR_DATA, M.MAR_HORA ";


  return await queryDB(sql);
}

module.exports = { listarMarcacoes };
